previewsEnabled: true
services:
  - type: web
    name: entangle-server
    env: node
    region: oregon
    plan: starter
    buildCommand: 'npm install && npm run build'
    startCommand: 'npm run prod --ws'
    numInstances: 1
    envVars:
      - key: NODE_VERSION
        value: 16.15.1
      - key: DATABASE_URL
        fromDatabase:
          name: entangle-db
          property: connectionString

databases:
  - name: entangle-db
    databaseName: db